// <auto-generated />
namespace Ganedata.Warehouse.PropertiesSync.SyncData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedCurrentOrFutureTenantForTenants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCurrentOrFutureTenantForTenants));
        
        string IMigrationMetadata.Id
        {
            get { return "201705161302372_AddedCurrentOrFutureTenantForTenants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
