//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganedata.Warehouse.PropertiesSync.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host_Tenants
    {
        public string TCODE { get; set; }
        public string TTYCODE { get; set; }
        public bool TTYLOCK { get; set; }
        public string TNAME { get; set; }
        public string TSALU { get; set; }
        public string TADD1 { get; set; }
        public string TADD2 { get; set; }
        public string TADD3 { get; set; }
        public string TADD4 { get; set; }
        public string TPSTCD { get; set; }
        public string TTELHOME { get; set; }
        public string TTELWK1 { get; set; }
        public string TTELWK2 { get; set; }
        public string TTELFAX { get; set; }
        public string TTELMOBL { get; set; }
        public string TE_MAIL { get; set; }
        public string TSTATUS { get; set; }
        public bool TTHEAD { get; set; }
        public string TTHDCODE { get; set; }
        public string TBRANCH { get; set; }
        public string TNOTES { get; set; }
        public string TUSERNT1 { get; set; }
        public string TUSERNT2 { get; set; }
        public string TUSERNT3 { get; set; }
        public string TUSERNT4 { get; set; }
        public Nullable<System.DateTime> TADDED { get; set; }
        public Nullable<int> TCLEARANCE { get; set; }
        public Nullable<int> TCLEARANCEC { get; set; }
        public Nullable<int> TCLEARANCES { get; set; }
        public Nullable<int> TCLEARANCEA { get; set; }
        public Nullable<int> TCLEARANCEB { get; set; }
        public string TRECTYPE { get; set; }
        public bool TBKCHK { get; set; }
        public bool TEMCHK { get; set; }
        public string TEMNAME { get; set; }
        public string TEMSALU { get; set; }
        public string TEMADD1 { get; set; }
        public string TEMADD2 { get; set; }
        public string TEMADD3 { get; set; }
        public string TEMADD4 { get; set; }
        public string TEMPSTCD { get; set; }
        public string TEMTEL { get; set; }
        public bool TATCHK { get; set; }
        public string TATNAME { get; set; }
        public string TATSALU { get; set; }
        public string TATADD1 { get; set; }
        public string TATADD2 { get; set; }
        public string TATADD3 { get; set; }
        public string TATADD4 { get; set; }
        public string TATPSTCD { get; set; }
        public string TATTEL { get; set; }
        public bool TKNCHK { get; set; }
        public string TKNNAME { get; set; }
        public string TKNSALU { get; set; }
        public string TKNADD1 { get; set; }
        public string TKNADD2 { get; set; }
        public string TKNADD3 { get; set; }
        public string TKNADD4 { get; set; }
        public string TKNPSTCD { get; set; }
        public string TKNTEL { get; set; }
        public bool TCHCHK { get; set; }
        public string TCHNAME { get; set; }
        public string TCHSALU { get; set; }
        public string TCHADD1 { get; set; }
        public string TCHADD2 { get; set; }
        public string TCHADD3 { get; set; }
        public string TCHADD4 { get; set; }
        public string TCHPSTCD { get; set; }
        public string TCHTEL { get; set; }
        public string LockID { get; set; }
        public Nullable<decimal> TRNTBFWD { get; set; }
        public Nullable<decimal> TGRTBFWD { get; set; }
        public Nullable<decimal> TDEPBFWD { get; set; }
        public Nullable<decimal> TSTLBFWD { get; set; }
        public Nullable<decimal> TSCGBFWD { get; set; }
        public Nullable<decimal> TINSBFWD { get; set; }
        public Nullable<decimal> TMANBFWD { get; set; }
        public Nullable<decimal> TWRTBFWD { get; set; }
        public Nullable<decimal> TSUNBFWD { get; set; }
        public Nullable<decimal> TADPBFWD { get; set; }
        public Nullable<decimal> TTENBFWD { get; set; }
        public Nullable<decimal> TADMBFWD { get; set; }
        public Nullable<decimal> TSTFBFWD { get; set; }
        public Nullable<float> TSharedPer { get; set; }
        public Nullable<decimal> TMRentMin { get; set; }
        public Nullable<decimal> TMRentMax { get; set; }
        public Nullable<int> TMNum1Min { get; set; }
        public Nullable<int> TMNum1Max { get; set; }
        public Nullable<int> TMNum2Min { get; set; }
        public Nullable<int> TMNum2Max { get; set; }
        public Nullable<int> TMNum3Min { get; set; }
        public Nullable<int> TMNum3Max { get; set; }
        public Nullable<int> TMNum4Min { get; set; }
        public Nullable<int> TMNum4Max { get; set; }
        public Nullable<System.DateTime> TEXPDATE { get; set; }
        public Nullable<decimal> TFIXEDAMOUNT { get; set; }
        public string TFIXEDPER { get; set; }
        public Nullable<System.DateTime> TFIXEDDATE { get; set; }
        public bool TADDEDBFBAL { get; set; }
        public bool TPrintRec { get; set; }
        public bool TCalcRents { get; set; }
        public bool TFirstInv { get; set; }
        public Nullable<System.DateTime> TReqBy { get; set; }
        public string TInvDemHeader { get; set; }
        public string TInvDemFooter { get; set; }
        public string TPfInvDemHeader { get; set; }
        public string TPfInvDemFooter { get; set; }
        public Nullable<decimal> TAgRent { get; set; }
        public Nullable<decimal> TAgDep { get; set; }
        public bool InMatching { get; set; }
        public bool TEXPORTFLAG { get; set; }
        public Nullable<System.DateTime> TEXPORTDATE { get; set; }
        public Nullable<System.DateTime> TIMPORTDATE { get; set; }
        public bool TEMailPreferred { get; set; }
        public bool TSMSPreferred { get; set; }
        public bool TPostPreferred { get; set; }
        public bool TSMSMMS { get; set; }
        public string PayeeName { get; set; }
        public string CompanyName { get; set; }
        public string EnquirySource { get; set; }
        public string TPAYTYPE { get; set; }
        public byte[] TDateTimeStamp { get; set; }
        public Nullable<int> DDProcessDay { get; set; }
        public Nullable<bool> DDBankDetailsValidated { get; set; }
        public string DDBankRef { get; set; }
        public string TFNAME { get; set; }
        public string TFSALU { get; set; }
        public string TFADD1 { get; set; }
        public string TFADD2 { get; set; }
        public string TFADD3 { get; set; }
        public string TFADD4 { get; set; }
        public string TFPSTCD { get; set; }
        public bool TUSEFWD { get; set; }
        public string TINNAME { get; set; }
        public string TINADD1 { get; set; }
        public string TINADD2 { get; set; }
        public string TINADD3 { get; set; }
        public string TINADD4 { get; set; }
        public string TINPSTCD { get; set; }
        public string TINTEL { get; set; }
        public string StandingOrderReference { get; set; }
        public Nullable<System.DateTime> TExclPropAvailBefore { get; set; }
        public int Id { get; set; }
        public int MOAppBranch { get; set; }
        public bool MOAppShared { get; set; }
        public Nullable<int> MOBranch { get; set; }
        public string TRPNAME { get; set; }
        public string TRPADD1 { get; set; }
        public string TRPADD2 { get; set; }
        public string TRPADD3 { get; set; }
        public string TRPADD4 { get; set; }
        public string TRPPSTCD { get; set; }
        public string TRPTEL { get; set; }
        public string TPTADD1 { get; set; }
        public string TPTADD2 { get; set; }
        public string TPTADD3 { get; set; }
        public string TPTADD4 { get; set; }
        public string TPTPSTCD { get; set; }
        public string TPTTEL { get; set; }
        public string TNegotiator { get; set; }
        public Nullable<int> TCategory { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool exportable { get; set; }
        public string TEnquirySource { get; set; }
        public bool TMoveItEnabled { get; set; }
    }
}
