//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganedata.Warehouse.PropertiesSync.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLandlordContractor
    {
        public int ID { get; set; }
        public string LCode { get; set; }
        public string CCode { get; set; }
        public string Description { get; set; }
    }
}
