--SELECT 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(schema_id)) + '.' + QUOTENAME(t.name) + ' ALTER COLUMN ' + QUOTENAME(c.name) + ' datetime2'
--FROM sys.tables AS t
--INNER JOIN sys.columns c ON t.OBJECT_ID = c.OBJECT_ID
--WHERE c.name LIKE 'DateCreated'

ALTER TABLE [dbo].[ProductSCCCodes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductReceipeMasters] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[StockTakeSnapshots] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[StockTakes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductLocationStockLevel] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[MarketRouteAssociations] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthUserLoginActivities] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Account] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthUserprofiles] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AccountAddresses] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantEmailConfigs] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[MarketJobs] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[EmployeeGroups] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Groups] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AccountContacts] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[EmployeeRoles] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Roles] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[JobTypes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Orders] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[OrderNotes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Resources] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[OrderProcesses] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ConsignmentTypes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ResourceShifts] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[OrderProcessDetails] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[PProperties] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Tenants] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[PLandlords] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthUsers] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ReportTypes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthPermissions] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[SLAPriorits] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthActivities] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthActivityGroupMaps] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[AuthActivityGroups] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantLocations] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Terminals] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TerminalsLogs] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[InventoryStocks] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductMaster] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[PTenants] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[GlobalDepartments] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ResourceRequests] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[OrderDetails] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Shifts] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductAccountCodes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[StockTakeScanLogs] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantConfigs] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Pallets] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantContacts] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[PalletsDispatches] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantCurrencies] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[MarketVehicles] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Markets] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[MarketRoutes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[TenantProfiles] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[MarketRouteCustomers] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[Locations] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[LocationGroups] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[LocationTypes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductLocations] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[InventoryTransactions] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[InventoryTransactionTypes] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductSerialis] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductAttributeValuesMaps] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductAttributeValues] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductGroups] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductKitMaps] ALTER COLUMN [DateCreated] datetime2
ALTER TABLE [dbo].[ProductPriceLevels] ALTER COLUMN [DateCreated] datetime2