// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stocktakeflagsforterminalsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stocktakeflagsforterminalsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201812221013091_stocktake-flags-for-terminals-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
