// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PriceGroupsPostageTypesChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceGroupsPostageTypesChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201805291059282_PriceGroups-PostageTypes-Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
