// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LastQty_In_InventoryTransactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastQty_In_InventoryTransactions));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221636037_LastQty_In_InventoryTransactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
