// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JobTypeIsDeletedAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobTypeIsDeletedAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201807231530447_JobType-IsDeleted-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
