// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class invoicenumberaddedinorderprocess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(invoicenumberaddedinorderprocess));
        
        string IMigrationMetadata.Id
        {
            get { return "201905252313406_invoicenumber-addedin-orderprocess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
