// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderDetailIdchangedtoOrderProcessDetailIdinPalletProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderDetailIdchangedtoOrderProcessDetailIdinPalletProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201903141059339_OrderDetailId-changed-to-OrderProcessDetailId-in-PalletProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
